### ISSUE TITLE
Missing classes detected while running R8

### ISSUE THREAD

**Issue by mzuzic-maidea** [shivbo96/otp_pin_field#22] opened 2024-09-25 08:07 UTC
Building on new Flutter and dart I get R8 Build error.

Versions are here:
```
# build.gradle
dependencies {
    implementation "com.google.android.material:material:1.9.0"
    implementation platform('com.google.firebase:firebase-bom:32.3.1')
    implementation 'com.google.firebase:firebase-analytics-ktx'
    implementation 'com.android.support:multidex:2.0.1'
    implementation 'com.google.android.gms:play-services-auth:21.2.0'
}

# settings.gradle
plugins {
    id "dev.flutter.flutter-plugin-loader" version "1.0.0"
    id "com.android.application" version "8.1.1" apply false
    id "org.jetbrains.kotlin.android" version "1.9.10" apply false
    id "com.google.gms.google-services" version "4.4.2" apply false
    id "com.google.firebase.crashlytics" version "2.9.9" apply false
}
```

```
> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.24.3, on Microsoft Windows [Version 10.0.22631.3880], locale hr-HR)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[!] Android Studio (version 2022.3)
    X Unable to find bundled Java version.
[√] Android Studio (version 2023.3)
[√] IntelliJ IDEA Ultimate Edition (version 2024.1)
[√] Connected device (2 available)
[√] Network resources

! Doctor found issues in 1 category.
```

Build error

```
> flutter build apk  --release --target-platform android-arm,android-arm64,android-x64 --split-per-abi

Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Font asset "CupertinoIcons.ttf" was tree-shaken, reducing it from 257628 to 1268 bytes (99.5% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.
Font asset "MaterialIcons-Regular.otf" was tree-shaken, reducing it from 1645184 to 7088 bytes (99.6% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.
ERROR: Missing classes detected while running R8. Please add the missing classes or apply additional keep rules that are generated in C:\********\build\app\outputs\mapping\release\missing_rules.txt.        
ERROR: R8: Missing class com.google.android.gms.auth.api.credentials.Credential (referenced from: boolean com.shivam.otp_pin_field.OtpPinFieldPlugin$activityResultListener$1.onActivityResult(int, int, android.content.Intent))
Missing class com.google.android.gms.auth.api.credentials.CredentialsApi (referenced from: void com.shivam.otp_pin_field.OtpPinFieldPlugin.requestHint())
Missing class com.google.android.gms.auth.api.credentials.HintRequest$Builder (referenced from: void com.shivam.otp_pin_field.OtpPinFieldPlugin.requestHint())
Missing class com.google.android.gms.auth.api.credentials.HintRequest (referenced from: void com.shivam.otp_pin_field.OtpPinFieldPlugin.requestHint())

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:minifyReleaseWithR8'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.R8Task$R8Runnable
   > Compilation failed to complete

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 45s
Running Gradle task 'assembleRelease'...                           45,7s
Gradle task assembleRelease failed with exit code 1
```

**Comment by shivbo96** [comment] 2024-10-21 14:02
Hi @mzuzic-maidea ,

Thank you for reporting the issue!

The R8 build error you're encountering is due to some missing classes related to `com.google.android.gms.auth.api.credentials` in the `OtpPinFieldPlugin`. This issue likely stems from the ProGuard/R8 configuration that is stripping out required classes during the build process.

### Potential Fixes:

1. **Add ProGuard Keep Rules:**
   You may need to add the missing keep rules for the classes being stripped out. You can find those missing rules in the path mentioned in the error: `C:\********\build\app\outputs\mapping\release\missing_rules.txt`. 

   Try adding the following rules to your `proguard-rules.pro` file:
   ```pro
   -keep class com.google.android.gms.auth.api.credentials.** { *; }
   -keep class com.google.android.gms.auth.api.credentials.CredentialsApi { *; }
   -keep class com.google.android.gms.auth.api.credentials.HintRequest$Builder { *; }
   -keep class com.google.android.gms.auth.api.credentials.HintRequest { *; }
   ```

2. **Update Google Play Services Auth Library:**
   Ensure that you are using the latest version of the `play-services-auth` library. Sometimes build issues can be caused by compatibility problems with older versions. Try updating your `build.gradle` to use the latest version:
   ```gradle
   implementation 'com.google.android.gms:play-services-auth:21.3.0'
   ```

3. **Check Your Multidex Configuration:**
   You are using `multidex`. Make sure it's properly configured in your `build.gradle` file:
   ```gradle
   android {
       defaultConfig {
           multiDexEnabled true
       }
   }
   ```

4. **Run with Debug Options:**
   If the above steps don’t resolve the issue, you can try running the build with `--stacktrace`, `--info`, or `--debug` for more detailed logs to further investigate the issue.

Let me know if these steps help resolve the issue or if you need further assistance!

Best regards

**Comment by shivbo96** [comment] 2024-10-24 14:15
Hi @mzuzic-maidea ,

We are closing this ticket as the "Missing classes detected while running R8" issue is not related directly to the `otp_pin_field` package itself but is due to missing ProGuard or R8 rules for the required Google Play services libraries in your project.

### Reason for Closing:
This issue occurs because certain classes related to `com.google.android.gms.auth.api.credentials` (used for SMS hint requests) are being stripped during the minification process with R8. To resolve this, you need to include the correct ProGuard rules in your project configuration to retain these classes. You can add the following rules in your `proguard-rules.pro` file:

```pro
-keep class com.google.android.gms.auth.api.credentials.** { *; }
```

This will prevent R8 from stripping out the necessary classes and should resolve the issue in your project.

Since the problem stems from the project’s configuration and not from the package itself, we’ll be closing this issue. Feel free to reopen it if you encounter any package-related problems, and thank you for your understanding!

Best regards

**Closed** 2024-10-24 14:15 UTC
